change_ball_dir = False

isServed = False

# player Run Speed
PIXEL_PER_METER = (10.0 / 0.3)  # 10 pixel 30 cm
PLAYER_RUN_SPEED_KMPH = 20.0  # Km / Hour
PLAYER_RUN_SPEED_MPM = (PLAYER_RUN_SPEED_KMPH * 1000.0 / 60.0)
PLAYER_RUN_SPEED_MPS = (PLAYER_RUN_SPEED_MPM / 60.0)
PLAYER_RUN_SPEED_PPS = (PLAYER_RUN_SPEED_MPS * PIXEL_PER_METER)

#ball Speed
BALL_SPEED_KMPH = 50.0  # Km / Hour
BALL_SPEED_MPM = (BALL_SPEED_KMPH * 1000.0 / 60.0)
BALL_SPEED_MPS = (BALL_SPEED_MPM / 60.0)
BALL_SPEED_PPS = (BALL_SPEED_MPS * PIXEL_PER_METER)